[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.14.0"
ic-cdk-macros = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
getrandom = { version = "0.2", default-features = false, features = ["custom"] }
ic-http-certification = "3.0"
evm-rpc-canister-types = { version = "5.0.1", default-features = false }
ic-web3-rs = { git = "https://github.com/horizonx-tech/ic-web3-rs", default-features = false } 
