[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.14.0"
ic-cdk-macros = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
getrandom = { version = "0.2", features = ["js"] }
ic-http-certification = "3.0"
ic-evm-utils = "4.0.0"
evm-rpc-canister-types = "5.0.1"
ethers-core = "2.0.14"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] } 
